# Logger level: debug, info, warn, error
log_level = "info"

# Webhook service to accept external notifications.
[webhook]
# Listen address, e.g., "127.0.0.1:2018"
listen = "127.0.0.1:2018"
# Bearer token to authenticate with (minimal length is 20 bytes).
# e.g., openssl rand -base64 33
token = "???"

# The IRC to interact with.
[irc]
# Nickname
nick = "dflybot"
# Server address
server = "irc.underworld.no"
# Server port
port = 6697
# Whether to SSL?
ssl = true
# Channels to join (must prefix with '#') and the list of nicknames to auto-op.
[irc.channels]
"#dragonflybsd" = [
	"aly", "aly-", "aly_",
	"dillon", "swildner", "tuxillo",
]

# Telegram settings.
[telegram]
# The bot token.
token = "???"
# The Chat IDs where to post messages.
chats = [???, ???]
