# Logger level: debug, info, warn, error
log_level = "info"

# Webhook service to accept external notifications.
[webhook]
# Listen address, e.g., "127.0.0.1:2018"
listen = "127.0.0.1:2018"
# Bearer token to authenticate with (minimal length is 20 bytes).
# e.g., openssl rand -base64 33
token = "???"

# The IRC to interact with.
[irc]
# My nickname
nick = "dflybot"
# Server address
server = "irc.underworld.no"
# Server port
port = 6697
# Whether to use SSL?
ssl = true
# List of channels to join
[[irc.channels]]
# The channel name (must prefix with '#')
name = "#dragonflybsd"
# The usernames and passwords to authenticate the "!opme" command
# Usage:
# sh$ t=$(date +%s)
# sh$ mac=$(printf $username:$t | openssl mac -digest SHA256 -macopt key:$password HMAC)
# irc> !opme $username:$t:$mac
[irc.channels.op_me]
# username = password

# Telegram settings.
[telegram]
# The bot token.
token = "???"
# The Chat IDs where to post messages.
# NOTE: To obtain this Chat ID:
# 1. Fill the token above and start this program;
# 2. Search the bot on Telegram and start a chat;
# 3. Send "/start" and it will tell the Chat ID;
# To obtain the Chat ID of a group chat, add the bot to the group and
# send "/start" to the bot.
chats = [???, ???]
